version: '3.1'

services:

    db:
        image: mysql:5.7
        container_name: mysql
        command: --disable-partition-engine-check
        restart: always
        # volumes: 
        #     - ./mysql/data:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=DBCatalogo
            - MYSQL_ROOT_PASSWORD=shilton@70
        networks: 
            - catalogo-network
        ports: 
            - 3306:3306

networks: 
    catalogo-network:
        driver: bridge